apiVersion: v1
kind: Deployment
metadata:
  name: java
spec: 
  replicas: 1
  template:
    metadata:
      labels:
          app: java
    spec:
      containers:
        - name: java-app
          image: princysearce/java-app:v1
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 300Mii
    ports:
      - name: java-port
        containerPort: 80
