apiVersion: v1
kind: Service
metadata:
  labels:
    app: java
  name: java
  namespace: development
spec:
  ports:
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: java
  type: LoadBalancer
