apiVersion: v1
kind: Service
metadata:
  labels:
    app: java
  name: java
  namespace: development
spec:
  ports:
  - nodePort: 30500
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: java
  type: LoadBalancer
