
apiVersion: v1
kind: Service
metadata:
  labels:
    app: python
  name: python
  namespace: development
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: python
  type: LoadBalancer
